version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "mozes721/budget-backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "mozes721/budget-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"